// Sigma Pack seed script — idempotent.
// Seeds the 3 subscription plans and all tools from db/tools.json.
// Icons are original letter-marks generated by lib/icons.ts (never real product logos).
//
// Usage (from project root):
//   DATABASE_URL=postgresql://... node db/seed.ts
//
// Node 24 can run this TypeScript directly via type stripping.
// Keep this file free of enums/namespaces so type stripping works.

import { neon } from '@neondatabase/serverless';
import { letterIcon } from '../lib/icons.ts';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL || DATABASE_URL.trim() === '') {
  console.error(
    'ERROR: DATABASE_URL is not set.\n' +
    'Run with your Neon connection string, e.g.:\n' +
    '  DATABASE_URL=postgresql://user:pass@host/dbname node db/seed.ts'
  );
  process.exit(1);
}

const sql = neon(DATABASE_URL);

const PLANS = [
  {
    slug: 'monthly',
    name: 'Monthly',
    months: 1,
    price_pkr: 799,
    features: [
      '100+ premium AI tools',
      'All categories unlocked',
      'WhatsApp support',
      'Cancel anytime',
    ],
    sort: 1,
  },
  {
    slug: 'half-yearly',
    name: 'Half-Yearly',
    months: 6,
    price_pkr: 3999,
    features: [
      '100+ premium AI tools',
      'All categories unlocked',
      'WhatsApp support',
      'Cancel anytime',
      'Save 17% vs monthly',
    ],
    sort: 2,
  },
  {
    slug: 'yearly',
    name: 'Yearly',
    months: 12,
    price_pkr: 6999,
    features: [
      '100+ premium AI tools',
      'All categories unlocked',
      'WhatsApp support',
      'Cancel anytime',
      'Save 27% vs monthly',
      'Priority support',
    ],
    sort: 3,
  },
];

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

interface ToolRow {
  name: string;
  category: string;
  description: string;
  url: string;
}

async function main(): Promise<void> {
  // ---- plans (idempotent upsert by slug) ----
  for (const p of PLANS) {
    await sql`
      INSERT INTO plans (slug, name, months, price_pkr, features, active, sort)
      VALUES (${p.slug}, ${p.name}, ${p.months}, ${p.price_pkr},
              ${JSON.stringify(p.features)}::jsonb, true, ${p.sort})
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        months = EXCLUDED.months,
        price_pkr = EXCLUDED.price_pkr,
        features = EXCLUDED.features,
        active = true,
        sort = EXCLUDED.sort
    `;
  }
  console.log(`plans upserted: ${PLANS.length}`);

  // ---- tools (idempotent upsert by slug) ----
  const here = dirname(fileURLToPath(import.meta.url));
  const raw = readFileSync(join(here, 'tools.json'), 'utf8');
  const tools = JSON.parse(raw) as ToolRow[];

  let n = 0;
  for (let i = 0; i < tools.length; i++) {
    const t = tools[i];
    const slug = slugify(t.name);
    const icon = letterIcon(t.name);
    await sql`
      INSERT INTO tools (name, slug, category, description, icon_svg, url, active, sort)
      VALUES (${t.name}, ${slug}, ${t.category}, ${t.description},
              ${icon}, ${t.url}, true, ${i})
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        category = EXCLUDED.category,
        description = EXCLUDED.description,
        icon_svg = EXCLUDED.icon_svg,
        url = EXCLUDED.url,
        active = true,
        sort = EXCLUDED.sort
    `;
    n++;
  }
  console.log(`tools upserted: ${n}`);

  // ---- verify counts ----
  const planCount = await sql`SELECT count(*)::int AS c FROM plans`;
  const toolCount = await sql`SELECT count(*)::int AS c FROM tools`;
  console.log(`done. plans in db: ${planCount[0].c}, tools in db: ${toolCount[0].c}`);
}

main().catch((err) => {
  console.error('Seed failed:', err instanceof Error ? err.message : err);
  process.exit(1);
});
